### ISSUE TITLE
[Installation] Gentoo Instructions

### ISSUE THREAD

**Issue by leycec** [j4ln/wa2-lutris#2]
**OMG!** Firstly, thanks so much for this phenomenal endeavour. I recently finished Shōgo Kinugasa's [light novel *pièce-de-résistance* "Classroom of the Elite: Year 1"](https://myanimelist.net/manga/89357/Youkoso_Jitsuryoku_Shijou_Shugi_no_Kyoushitsu_e) and am now fiending for a new weeb summer blast-from-the-past blockbuster. Five minutes later, this repository summoned me. I am shocked and honoured to be the first GitHubber to star this. You deserve all the upvotes.

But why has the world neglected you for so long, "White Album 2"? I have no answers. Only more depressing questions. 

Secondly, I too author Lutris visual novel installers. You may remember me from such GitHub repositories as:

* [`fsnrnue`, the *Fate/stay night [Réalta Nua] Ultimate Edition… for Linux!* Lutris installer](https://github.com/leycec/fsnrnue).
* [`aokana-linux`, the *Ao no Kanata no Four Rhythm (Aokana)… for Linux!* Lutris installer](https://github.com/leycec/aokana-linux).

Is this all I have to show for forty years of hard labour on Planet Earth? Let's not answer that. :sob:

Thirdly, it'd be great if you could add the following Gentoo Linux-specific installation instructions to this repository's `README.md`. Without further ado...

## Enable Japanese locale

Unsurprisingly, these instructions are *almost* <sup>but not quite</sup> a verbatim copy of your Arch Linux-specific instructions:

* Gentoo:

```bash
sudo sed -i 's/^#ja_JP.UTF-8 UTF-8/ja_JP.UTF-8 UTF-8/' /etc/locale.gen
sudo locale-gen
emerge kochi-substitute ja-ipafonts noto-cjk
```

The final line is different enough to warrant distinct instructions, I think. 

## Install 32-bit GStreamer

Surprisingly, these instructions are quite different from all existing instructions for other Linux distributions. Gentoo just gotta be different, huh? :face_exhaling: 

* Gentoo:

```bash
USE="abi_x86_32" emerge --autounmask gst-plugins-{good,ugly,libav}
```

## Let's Get This Reading Party Started

Thanks again for your tremendous volunteerism and dedication to the just cause of Japanese visual novels (JVN), @j4ln. Most heroes may not wear capes, but I wouldn't be surprised if you do.

**Comment by j4ln** [comment]
Thanks for the kind words and Gentoo instructions @leycec!
