### ISSUE TITLE
Updated command for installing GStreamer on Fedora

### ISSUE THREAD

**Issue by cuanim** [j4ln/wa2-lutris#3]
For installing 32-bit GStreamer on Fedora, the correct command (atleast for now) is
`sudo dnf install -y gstreamer1-{plugins-{good,ugly},plugin-libav}.i686`
I think they changed the name from `gstreamer1-libav.i686` -> `gstreamer1-plugin-libav.i686`
Here's the gstreamer libav package: https://packages.fedoraproject.org/pkgs/gstreamer1-plugin-libav/gstreamer1-plugin-libav/

**Comment by j4ln** [comment]
Thanks for raising this!
