### ISSUE TITLE
Patch installer 403 error

### ISSUE THREAD

**Issue by OkabeZeroLink** [j4ln/wa2-lutris#4]
So, I pretty much prepared like you've said, but when the installer finished download the patch installer, it throws: FileNotFoundError(2, 'No such file or directory')

So, uh, what am I supposed to do? I also tried select the patch installer on my computer, also throws the same error

**Comment by j4ln** [comment]
Hey @OkabeZeroLink. I've attempted to reproduce this on the latest version of Lutris and I've been unable to get the same issue.

Can you get a debug output of the installation to help me look into the issue please. You can do this by starting Lutris through the terminal with `lutris -d`. When you install the game the terminal will contain information about the installation. Copy the logs from here to somewhere accessible and send me the link to them please.

**Comment by Okbzl** [comment]
Ok, so I've been able to solve this issue already, so you can close this if you want, but 2nd issue: The patch installer. In short: It gave me 403 error (i'm in vietnam, btw), thus I was unable to install the patch

**Comment by j4ln** [comment]
I've been able to reproduce the patch installer 403 error and have pushed a fix to the install script. The old patch installer is no longer supported according to a message in the Todokanai Discord so the script will instead now fetch and extract the full patch archive.

I've submitted the change to the Lutris website for approval. If you don't want to wait until it's approved you can install it with the install script in this repository via the terminal.

Resolved by https://github.com/j4ln/wa2-lutris/commit/69d130bd66f4831917b8b35676e30c20a264300d

**Comment by Okbzl** [comment]
It works, tysm. Also, not related to the issue, but can you also make an installer for the SC (Mini After Story) disc, too? Thanks in advance

**Comment by j4ln** [comment]
Awesome glad to hear its working now! I'll close this ticket down now.

I've opened a new issue #5 for the Mini After Story installer request and I'll take a look at it over the weekend for you.
